version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: bread_map
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    networks:
      - springboot-mysql-net

  app:
    container_name: ddb-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge