spring:
  lifecycle:
    timeout-per-shutdown-phase: 40s
  jpa:
    hibernate:
      use-new-id-generator-mappings: false # Hibernate id 생성 전략 여부
    #    show-sql: true
    open-in-view: false # OSIV
    properties:
      default_batch_fetch_size: 100
      hibernate:
        #        format_sql: true
        create_empty_composites:
          enabled: true # @Embbeded 전체 value 들이 null 이어도 null 로 나오지 않게
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 한건당
      maxRequestSize: 100MB # API 호출당
  mvc:
    throw-exception-if-no-handler-found: true # NoHandlerFoundException Exception throw 여부
  web:
    resources:
      add-mappings: false # 정적 리소스 조회 여부
  data:
    redis:
      repositories:
        enabled: false # Spring Data Redis 저장소 기능
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

server:
  servlet:
    encoding:
      charset: UTF-8 # 어플리케이션에서 사용할 문자 인코딩
      force: true # 어플리케이션에서 지정한 인코딩을 요청과 응답에 강제 적용 여부

management:
  endpoint:
    health:
      enabled: true # health endpoint enable
  endpoints:
    enabled-by-default: false # 모든(shutdown 제외) endpoint enable 여부
    jmx:
      exposure:
        exclude: "*" # JMX 형태 endpoint 제외 대상
    web:
      exposure:
        include: health # 노출할 상태 정보
      base-path: /v1/actuator # endpoint 경로 (default)

cloud:
  aws:
    credentials:
      instanceProfile: true # AWS 인스턴스 프로필 사용 여부
    stack:
      auto: false # AWS CloudFormation 사용 여부

redis:
  poll-timeout:
    bakery-view: 2
    bakery-ranking-calculator: 2