spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTH_URL}
            token-uri: ${KAKAO_TOKEN_URL}
            user-info-uri: ${KAKAO_USER_INFO_URL}
            user-name-attribute: id

auth:
  token-secret: ${JWT_KEY}
  access-token-expiry: 1800000 # 30분
  refresh-token-expiry: 604800000 # 7일

cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'
  max-age: 3600

cloud:
  aws:
    credentials:
      instanceProfile: true
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false
    cloudFront:
      distributionDomain: ${S3_CLOUDFRONT}

logging:
  level:
    root: error