spring:
  jwt:
    secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    admin: jwtadminsecretkeyjwtadminsecretkeyjwtadminsecretkey
  datasource:
    url: jdbc:h2:mem:bread_map
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
    key:
      delete: delete
      recent: recent
      access: access
      refresh: refresh
      adminRefresh: adminRefresh
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          apple:
            client-name: Apple
            client-id: ${APPLE_ID}
            client-secret: ${APPLE_SECRET}
            redirect-uri: ${APPLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
#            client-authentication-method: client_secret_post
            scope:
              - openid
              - name
              - email
              - picture

        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTH_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id
          apple:
            authorization-uri: ${APPLE_AUTH_URI}
            token-uri: ${APPLE_TOKEN_URI}
            user-info-uri: ${APPLE_USER_INFO_URI}
            user-name-attribute: sub

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: s3-bucket
      default-path:
        comment: S3_DEFAULT_COMMENT
        like: S3_DEFAULT_LIKE
        report: S3_DEFAULT_REPORT
        flag: S3_DEFAULT_FLAG
    stack:
      auto: false
    cloudFront:
      distributionDomain: cloudfront

firebase:
  url: FIREBASE_URL
  path: FIREBASE_PATH
  scope: FIREBASE_SCOPE
  projectId: FIREBASE_PROJECTID
  message:
    path:
      user: FIREBASE_MESSAGE_PATH_USER
      review: FIREBASE_MESSAGE_PATH_REVIEW

sgis:
  key: SGIS_KEY
  secret: SGIS_SECRET