spring:
  jwt:
    secret: ${JWT_KEY}
    admin: ${JWT_ADMIN_KEY}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  #      idle-timeout: 300
  #      max-lifeitme: 300
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      default_batch_fetch_size: 100
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    key:
      delete: ${REDIS_KEY_DELETE}
      recent: ${REDIS_KEY_RECENT}
      access: ${REDIS_KEY_ACCESS}
      refresh: ${REDIS_KEY_REFRESH}
      admin-refresh: ${REDIS_KEY_ADMIN_REFRESH}
      bakery-review: ${REDIS_KEY_BAKERY_REVIEW}
      product-review: ${REDIS_KEY_PRODUCT_REVIEW}
      user-review: ${REDIS_KEY_USER_REVIEW}

oauth:
  google: ${GOOGLE_ID}
  kakao: ${KAKAO_ID}
  apple: ${APPLE_ID}

cloud:
  aws:
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}
      cloud-front: ${S3_CLOUDFRONT}
      default-bucket:
        image: ${S3_DEFAULT_BUCKET_IMAGE}
      default-image:
        bakery: ${S3_DEFAULT_IMAGE_BAKERY}
        comment: ${S3_DEFAULT_IMAGE_COMMENT}
        like: ${S3_DEFAULT_IMAGE_LIKE}
        report: ${S3_DEFAULT_IMAGE_REPORT}
        flag: ${S3_DEFAULT_IMAGE_FLAG}
        user: ${S3_DEFAULT_IMAGE_USER}

firebase:
  credentials: ${FIREBASE_CREDENTIALS}
  scope: ${FIREBASE_SCOPE}
  projectId: ${FIREBASE_PROJECTID}
  message:
    path:
      user: ${FIREBASE_MESSAGE_PATH_USER}
      review: ${FIREBASE_MESSAGE_PATH_REVIEW}

sgis:
  src: ${SGIS_SRC}
  dst1: ${SGIS_DST1}
  dst2: ${SGIS_DST2}
  key: ${SGIS_KEY}
  secret: ${SGIS_SECRET}
