spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: false

  profiles:
    include: local # dev # prod
