= 관리자 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== APIs
- 관리자 로그인 API
- 토큰 재발급 API
- 메뉴바 API
- 빵집 전체 조회 API
- 빵집 상세 조회 API
- 빵집 검색 API
- 빵집 위도 경도 조회 API
- 빵집 추가 API
- 빵집 수정 API
- 빵집 상품 삭제 API
- 빵집 관련 이미지 (대표 이미지, 메뉴제보 이미지, 리뷰 이미지) 조회 API
- 빵집 삭제 API
- 빵집 제보 전체 조회 API
- 빵집 제보 상세 조회 API
- 빵집 게시 상태 변경 API
- 리뷰 신고 전체 조회 API
- 리뷰 게시 상태 변경 API
- 유저 전체 조회 API
- 유저 차단 API

=== 관리자 로그인 API [POST]
operation::admin/login[snippets='http-request,request-fields,http-response,response-fields']

=== 토큰 재발급 API [POST]
operation::admin/reissue[snippets='http-request,request-fields,http-response,response-fields']

=== 메뉴바 API [GET]
operation::admin/bar[snippets='http-request,request-headers,http-response,response-fields']

=== 빵집 전체 조회 API [GET]
operation::admin/bakery/all[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 빵집 조회 API [GET]
operation::admin/bakery[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 빵집 검색 API [GET]
operation::admin/bakery/search[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 빵집 위도 경도 조회 API [GET]
operation::admin/bakery/location[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 빵집 추가 API [POST]
operation::admin/bakery/add[snippets='http-request,request-headers,request-parts,request-part-request-fields,http-response']

=== 빵집 수정 API [POST]
operation::admin/bakery/update[snippets='http-request,request-headers,path-parameters,request-parts,request-part-request-fields,http-response']

=== 빵집 상품 삭제 API [DELETE]
operation::admin/bakery/delete/product[snippets='http-request,request-headers,path-parameters,http-response']

=== 빵집 관련 이미지 (대표 이미지, 메뉴제보 이미지, 리뷰 이미지) 조회 API [GET]
operation::admin/bakery/image[snippets='http-request,request-headers,path-parameters,request-parameters,http-response,response-fields']

=== 빵집 삭제 API [DELETE]
operation::admin/bakery/delete[snippets='http-request,request-headers,path-parameters,http-response']

=== 빵집 제보 전체 조회 API [GET]
operation::admin/bakeryReport/all[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 빵집 제보 상세 조회 API [GET]
operation::admin/bakeryReport[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 빵집 제보 처리 상태 변경 API [PATCH]
operation::admin/bakeryReport/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 리뷰 신고 전체 조회 API [GET]
operation::admin/reviewReport/all[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 리뷰 게시 상태 변경 API [PATCH]
operation::admin/reviewReport/update[snippets='http-request,request-headers,path-parameters,http-response']

=== 유저 전체 조회 API [GET]
operation::admin/user/all[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 유저 차단 API [PATCH]
operation::admin/user/block[snippets='http-request,request-headers,path-parameters,http-response']
