ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== 소개
대동빵지도 API

=== Domain
|===
| 환경 | Domain

| 개발 서버|`http://localhost:8080`
| 운영 서버|`http://3.36.94.161`
|===


== 유저 API
- 토큰 재발급 API
- 프로필 조회 API
- 팔로우 API
- 언팔로우 API
- 팔로워 리스트 조회 API
- 팔로잉 리스트 조회 API

=== 토큰 재발급 API [POST]
operation::user/reissue[snippets='http-request,request-fields,http-response,response-fields']

=== 프로필 조회 API [GET]
operation::user/profile[snippets='http-request,request-headers,http-response,response-fields']

=== 팔로우 API [POST]
operation::user/follow[snippets='http-request,request-headers,request-fields,http-response']

=== 언팔로우 API [DELETE]
operation::user/unfollow[snippets='http-request,request-headers,request-fields,http-response']

=== 팔로워 리스트 조회 [GET]
operation::user/follower[snippets='http-request,request-headers,http-response']

=== 팔로잉 리스트 조회 [GET]
operation::user/following[snippets='http-request,request-headers,http-response']

== 빵집 API
- 빵집 지도 API
- 빵집 지도 필터 API
- 빵집 단건 조회 API
- 빵집 수정 요청 API
- 빵집 삭제 요청 API
- 빵집 추가 요청 API
- 빵 추가 요청 API

=== 빵집 지도 API [GET]
operation::bakery/find/default[snippets='http-request,request-parameters,http-response,response-fields']

=== 빵집 지도 필터 API [GET]
operation::bakery/find/filter[snippets='http-request,request-parameters,http-response,response-fields']

=== 빵집 단건 조회 API [GET]
operation::bakery/find[snippets='http-request,path-parameters,http-response,response-fields']

=== 빵집 수정 요청 API [POST]
operation::bakery/report/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 빵집 삭제 요청 API [POST]
operation::bakery/report/delete[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== 빵집 추가 요청 API [POST]
operation::bakery/report/add[snippets='http-request,request-headers,request-fields,http-response']

=== 빵 추가 요청 API [POST]
operation::bakery/report/bread[snippets='http-request,request-headers,path-parameters,request-parts,request-part-request-fields,http-response']

== 깃발 API
- 깃발 간단 리스트 조회 API
- 깃발 리스트 조회 API,
- 깃발 추가 API
- 깃발 삭제 API
- 깃발 업데이트 API,
- 깃발에 추가된 빵집 리스트 조회 API
- 깃발에 빵집 추가 API
- 깃발에 등록된 빵집 삭제 API

=== 깃발 간단 리스트 조회 API [GET]
operation::flag/findSimple[snippets='http-request,request-headers,http-response,response-fields']

=== 깃발 리스트 조회 API [GET]
operation::flag/find[snippets='http-request,request-headers,http-response,response-fields']

=== 깃발 추가 API [POST]
operation::flag/add[snippets='http-request,request-headers,request-fields,http-response']

=== 깃발 삭제 API [DELETE]
operation::flag/delete[snippets='http-request,request-headers,path-parameters,http-response']

=== 깃발 업데이트 API [PATCH]
operation::flag/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 깃발에 추가된 빵집 리스트 조회 [GET]
operation::flag/bakeryFind[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 깃발에 빵집 추가 API [POST]
operation::flag/bakeryAdd[snippets='http-request,request-headers,path-parameters,http-response']

=== 깃발에 등록된 빵집 삭제 [DELETE]
operation::flag/bakeryDelete[snippets='http-request,request-headers,path-parameters,http-response']

== 리뷰 API

- 리뷰 간단 조회 API
- 리뷰 전체 조회 API
- 리뷰 상세 조회 API
- 리뷰 추가 API
- 리뷰 삭제 API
//- 유저 리뷰 전체 조회 API
- 리뷰 좋아요 API
- 리뷰 좋아요 취소 API
- 리뷰 댓글 전체 조회 API
- 리뷰 댓글 추가 API
- 리뷰 댓글 삭제 API
- 리뷰 댓글 좋아요 API
- 리뷰 댓글 좋아요 취소 API

=== 리뷰 간단 조회 API [GET]
operation::review/get/simple[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 리뷰 전체 조회 API [GET]
operation::review/get/all[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 리뷰 상세 조회 API [GET]
operation::review/get[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 리뷰 추가 API [POST]
operation::review/add[snippets='http-request,request-headers,path-parameters,request-parts,request-part-request-fields,http-response']

=== 리뷰 삭제 API [DELETE]
operation::review/remove[snippets='http-request,request-headers,path-parameters,http-response']

//=== 유저 리뷰 전체 조회 API [GET]
//operation::review/get/user[snippets='http-request,request-headers,http-response,response-fields']

=== 리뷰 좋아요 API [POST]
operation::review/like[snippets='http-request,request-headers,path-parameters,http-response']

=== 리뷰 좋아요 취소 API [DELETE]
operation::review/unlike[snippets='http-request,request-headers,path-parameters,http-response']

=== 리뷰 댓글 전체 조회 API [GET]
operation::review/comment/all[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 리뷰 댓글 추가 API [POST]
operation::review/comment/add[snippets='http-request,request-headers,path-parameters,http-response']

=== 리뷰 댓글 삭제 API [DELETE]
operation::review/comment/remove[snippets='http-request,request-headers,path-parameters,http-response']

=== 리뷰 댓글 좋아요 API [POST]
operation::review/comment/like[snippets='http-request,request-headers,path-parameters,http-response']

=== 리뷰 댓글 좋아요 취소 API [DELETE]
operation::review/comment/unlike[snippets='http-request,request-headers,path-parameters,http-response']
