ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== 소개
DaeDongBread API

=== Domain
|===
| 환경 | Domain

| 개발 서버|`http://localhost:8080`
| 운영 서버|`https://api.moodpic.kr`
|===


== 유저 API
토큰 재발급 API

=== 토큰 재발급 [POST]
operation::user/reissue[snippets='http-request,request-fields,http-response,response-fields']

== 빵집 API
빵집 지도 API, 빵집 지도 필터 API, 빵집 단건 조회 API,
빵집 가고싶어요 API, 빵집 가고싶어요 취소 API,
빵집 가봤어요 API, 빵집 가봤어요 취소 API

=== 빵집 지도 [GET]
operation::bakery/find/default[snippets='http-request,request-parameters,http-response,response-fields']

=== 빵집 지도 필터 [GET]
operation::bakery/find/filter[snippets='http-request,request-parameters,http-response,response-fields']

=== 빵집 단건 조회 [GET]
operation::bakery/find[snippets='http-request,path-parameters,http-response,response-fields']

== 깃발 API
깃발 간단 리스트 조회 API, 깃발 리스트 조회 API,
깃발 추가 API, 깃발 삭제 API, 깃발 업데이트 API,
깃발에 추가된 빵집 리스트 조회 API, 깃발에 빵집 추가 API, 깃발에 등록된 빵집 삭제 API

=== 깃발 간단 리스트 조회 API [GET]
operation::flag/findSimple[snippets='http-request,request-headers,http-response,response-fields']

=== 깃발 리스트 조회 API [GET]
operation::flag/find[snippets='http-request,request-headers,http-response,response-fields']

=== 깃발 추가 API [POST]
operation::flag/add[snippets='http-request,request-headers,request-fields,http-response']

=== 깃발 삭제 API [DELETE]
operation::flag/delete[snippets='http-request,request-headers,path-parameters,http-response']

=== 깃발 업데이트 API [PATCH]
operation::flag/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 깃발에 추가된 빵집 리스트 조회 [GET]
operation::flag/bakeryFind[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 깃발에 빵집 추가 API [POST]
operation::flag/bakeryAdd[snippets='http-request,request-headers,path-parameters,http-response']

=== 깃발에 등록된 빵집 삭제 [DELETE]
operation::flag/bakeryDelete[snippets='http-request,request-headers,path-parameters,http-response']
