ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== 소개
DaeDongBread API

=== Domain
|===
| 환경 | Domain

| 개발 서버|`http://localhost:8080`
| 운영 서버|`http://3.36.94.161`
|===


== 유저 API
토큰 재발급 API

=== 토큰 재발급 [POST]
operation::user/reissue[snippets='http-request,request-fields,http-response,response-fields']

== 빵집 API
빵집 지도 API, 빵집 지도 필터 API, 빵집 단건 조회 API,
빵집 가고싶어요 API, 빵집 가고싶어요 취소 API,
빵집 가봤어요 API, 빵집 가봤어요 취소 API

=== 빵집 지도 [GET]
operation::bakery/find/default[snippets='http-request,request-parameters,http-response,response-fields']

//=== 빵집 지도 필터 [GET]
//operation::bakery/filter[snippets='http-request,request-fields,http-response,response-fields']

=== 빵집 단건 조회 [GET]
operation::bakery/find[snippets='http-request,path-parameters,http-response,response-fields']

=== 빵집 가봤어요 [PATCH]
operation::bakery/heart[snippets='http-request,request-headers,path-parameters,http-response']

=== 빵집 가봤어요 취소 [PATCH]
operation::bakery/unHeart[snippets='http-request,request-headers,path-parameters,http-response']

=== 빵집 가고싶어요 [PATCH]
operation::bakery/flag[snippets='http-request,request-headers,path-parameters,http-response']

=== 빵집 가고싶어요 취소 [PATCH]
operation::bakery/unFlag[snippets='http-request,request-headers,path-parameters,http-response']
