= 알림 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== APIs
- 알림 토큰 추가 API
- 알림 토큰 수정 API
- 알림 토큰 삭제 API
- 알림 상태 조회 API
- 알림 상태 변경 API
- 오늘 알림 조회 API
- 이번주 알림 조회 API
- 이번주 이전 알림 조회 API

=== 알림 토큰 추가 API [POST]
operation::notice/token/add[snippets='http-request,request-headers,request-fields,http-response']

=== 알림 토큰 수정 API [PATCH]
operation::notice/token/update[snippets='http-request,request-headers,request-fields,http-response']

=== 알림 토큰 삭제 API [DELETE]
operation::notice/token/delete[snippets='http-request,request-headers,request-fields,http-response']

=== 알림 상태 조회 API [GET]
operation::notice/token/alarm[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 알림 상태 변경 API [PATCH]
operation::notice/token/alarm/update[snippets='http-request,request-headers,request-fields,http-response']

=== 오늘 알림 조회 API [GET]
오늘 알림 조회

operation::notice[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 이번주 알림 조회 API [GET]
엔드포인트 : /notice/week, 이외에는 오늘 알림 조회와 같음

이번주 월요일부터 어제까지의 알림 조회

=== 이번주 이전 알림 조회 API [GET]
엔드포인트 : /notice/before, 이외에는 오늘 알림 조회와 같음

저번주 일요일 전의 알림 조회
