= 검색 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== APIs
- 자동 완성 API
- 검색 API

=== 검색 API [GET] New
operation::v2/search/keyword[snippets='http-request,request-parameters,http-response,response-fields']

=== 검색 API [GET] Old (/v2 API 호출 실패 시 조회)
operation::v1/search/search[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 자동완성 검색어 추천 API [GET]
operation::v2/search/suggestions[snippets='http-request,request-parameters,http-response,response-fields']

=== 인기검색어 검색 테스트 API [GET]
operation::v2/search/rank/[snippets='http-request,http-response,response-fields']

== OpenSearch Query 테스트용 End Point

=== Index에 data추가 API [POST]
operation::v1/search-engine/document[snippets='http-request,request-fields,http-response,response-fields']

=== 빵 상품명으로 검색 테스트 API [GET]
operation::v1/search-engine/document/bread[snippets='http-request,request-parameters,http-response,response-fields']

=== 빵집명으로 검색 테스트 API [GET]
operation::v1/search-engine/document/bakery[snippets='http-request,request-parameters,http-response,response-fields']

