= 유저 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

== APIs
- 토큰 재발급 API
- 프로필 조회 API
- 닉네임 업데이트 API
- 로그아웃 API
- 유저 탈퇴 API
- 팔로우 API
- 팔로워 삭제 API
- 팔로우 삭제 API
- 팔로워 리스트 조회 API
- 팔로잉 리스트 조회 API
- 차단 리스트 조회 API
- 차단 API
- 차단 해제 API

=== 토큰 재발급 API [POST]
operation::user/reissue[snippets='http-request,request-fields,http-response,response-fields']

=== 본인 프로필 조회 API [GET]
operation::user/me[snippets='http-request,request-headers,http-response,response-fields']

=== 타인 프로필 조회 API [GET]
operation::user/profile[snippets='http-request,request-headers,http-response,response-fields']

=== 닉네임 업데이트 API [PATCH]
operation::user/nickname[snippets='http-request,request-headers,request-parts,request-part-request-fields,http-response']

=== 로그아웃 API [POST]
operation::user/logout[snippets='http-request,request-headers,request-fields,http-response']

=== 유저 탈퇴 API [DELETE]
operation::user/delete[snippets='http-request,request-headers,http-response']

=== 팔로우 API [POST]
operation::user/follow[snippets='http-request,request-headers,request-fields,http-response']

=== 팔로우 삭제 API [DELETE]
operation::user/delete/follower[snippets='http-request,request-headers,request-fields,http-response']

=== 팔로잉 삭제 API [DELETE]
operation::user/delete/following[snippets='http-request,request-headers,request-fields,http-response']

=== 본인 팔로워 리스트 조회 [GET]
operation::user/me/follower[snippets='http-request,request-headers,http-response']

=== 본인 팔로잉 리스트 조회 [GET]
operation::user/me/following[snippets='http-request,request-headers,http-response']

=== 타인 팔로워 리스트 조회 [GET]
operation::user/follower[snippets='http-request,request-headers,http-response']

=== 타인 팔로잉 리스트 조회 [GET]
operation::user/following[snippets='http-request,request-headers,http-response']

=== 차단 리스트 조회 [GET]
operation::user/blockList[snippets='http-request,request-headers,http-response']

=== 차단 API [POST]
operation::user/block[snippets='http-request,request-headers,request-fields,http-response']

=== 차단 해제 API [DELETE]
operation::user/unblock[snippets='http-request,request-headers,request-fields,http-response']
