package com.depromeet.breadmapbackend.domain.bakery.ranking.mock;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import org.springframework.test.util.ReflectionTestUtils;

import com.depromeet.breadmapbackend.domain.bakery.ranking.ScoredBakery;
import com.depromeet.breadmapbackend.domain.bakery.ranking.ScoredBakeryRepository;

/**
 * ScoredBakeryRepositoryImpl
 *
 * @author jaypark
 * @version 1.0.0
 * @since 2023/07/02
 */
public class FakeScoredBakeryRepositoryImpl implements ScoredBakeryRepository {

	private static final AtomicLong autoGeneratedId = new AtomicLong(0);
	private static final List<ScoredBakery> data = Collections.synchronizedList(new ArrayList<>());
	private static final List<ScoredBakery> cachedData = Collections.synchronizedList(new ArrayList<>());

	@Override
	public int bulkInsert(final List<ScoredBakery> scoredBakeryList, final String weekOfMonthYear) {
		data.clear();
		scoredBakeryList.stream()
			.map(scoredBakery -> ScoredBakery.builder()
				.bakery(scoredBakery.getBakery())
				.bakeryRating(scoredBakery.getBakeryRating())
				.flagCount(scoredBakery.getFlagCount())
				.totalScore(scoredBakery.getTotalScore())
				.createdWeekOfMonthYear(scoredBakery.getCreatedWeekOfMonthYear())
				.build())
			.forEach(scoredBakery -> {
				ReflectionTestUtils.setField(scoredBakery, "id", autoGeneratedId.incrementAndGet());
				data.add(scoredBakery);
			});

		return data.size();
	}

	@Override
	public List<ScoredBakery> findCachedScoredBakeryByWeekOfMonthYear(final String weekOfMonthYear, final int size) {
		return cachedData.stream().sorted(Comparator.comparing(ScoredBakery::getTotalScore).reversed()
				.thenComparing((ScoredBakery scoredBakery) -> scoredBakery.getBakery().getId()))
			.limit(size)
			.toList();
	}

	@Override
	public List<ScoredBakery> findScoredBakeryByWeekOfMonthYear(final String weekOfMonthYear, final int size) {
		return data.stream().sorted(Comparator.comparing(ScoredBakery::getTotalScore).reversed()
				.thenComparing((ScoredBakery scoredBakery) -> scoredBakery.getBakery().getId()))
			.limit(size)
			.toList();
	}

	public static void prepareData(final List<ScoredBakery> scoredBakery) {
		data.addAll(scoredBakery);
	}

	public static void prepareCacheData(final List<ScoredBakery> scoredBakery) {
		cachedData.addAll(scoredBakery);
	}

	public static void clearData() {
		data.clear();
		cachedData.clear();
	}
}
