version: '3.8'
services:
  local-mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: local_bread_map
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '33065:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local