name: PROD_CI
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'README.md'

jobs:
  backend:
    name: CI with Gradle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17
        cache: gradle

    - name: Cache gradle modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
        
    - name: If failure then upload test reports
      if: failure()
      run: |
        TARBALL_BASENAME="r6-stats-report"
        TARBALL="$TARBALL_BASENAME.tar"
        echo 'Collecting the test report'
        find . -path '*/build/reports/tests' -type d \
          -exec tar rf "$TARBALL" \
            --xform="s:./:$TARBALL_BASENAME/:" \
            --xform='s:/build/reports/tests::' \
            {} ';'
        echo 'Compressing the test reports .. '
        gzip "$TARBALL"
        echo 'Uploading the test reports .. '
        curl -F "file=@$TARBALL.gz" 'https://file.io/'
        echo
        echo 'Download the test reports from the URL above.'
        
    - name: CI notification to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Backend CI
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
